import re
import os

from robot.api import logger  # type: ignore
from robot.libraries.BuiltIn import BuiltIn, EXECUTION_CONTEXTS  # type: ignore
from robotlibcore import DynamicCore  # type: ignore

from .keywords.waiter import ElementState
from .keywords.input import SelectAttribute, MouseButton, KeyboardModifier
from .keywords.playwright_state import SupportedBrowsers
from .playwright import Playwright
from .version import VERSION

class Browser:

    def add_style_tag(self, content): ...

    def auto_activate_pages(self): ...

    def check_checkbox(self, selector): ...

    def clear_text(self, selector): ...

    def click(self, selector): ...

    def click_with_options(self, selector, button=MouseButton.left, click_count='1', delay=None,
                           position_x=None, position_y=None, *modifiers): ...

    def close_all_browsers(self): ...

    def close_browser(self): ...

    def close_context(self): ...

    def close_page(self): ...

    def create_browser(self, browser=SupportedBrowsers.chromium, executablePath=None, args=None,
                       ignoreDefaultArgs=None, handleSIGINT=None, handleSIGTERM=None,
                       handleSIGHUP=None, timeout='30 seconds', env=None, headless=None,
                       devtools=None, proxy=None, downloadsPath=None, slowMo='0 seconds'): ...

    def create_context(self, hideRfBrowser=False, viewport=None, ignoreHTTPSErrors=None,
                       javaScriptEnabled=None, bypassCSP=None, userAgent=None, locale=None,
                       timezoneId=None, geolocation=None, permissions=None, extraHTTPHeaders=None,
                       offline=None, httpCredentials=None, deviceScaleFactor=None, isMobile=None,
                       hasTouch=None, colorScheme=None, acceptDownloads=None): ...

    def create_page(self, url=None): ...

    def deselect_options(self, selector): ...

    def execute_javascript_on_page(self, script): ...

    def fill_secret(self, selector, secret): ...

    def fill_text(self, selector, text): ...

    def focus(self, selector): ...

    def get_attribute(self, selector, attribute, assertion_operator=None,
                      assertion_expected=None): ...

    def get_browser_catalog(self): ...

    def get_checkbox_state(self, selector, assertion_operator=None, state=False): ...

    def get_element_count(self, selector, assertion_operator=None, expected_count='-1'): ...

    def get_page_state(self, assertion_operator=None, assertion_expected=None): ...

    def get_selected_options(self, selector, option_attribute=SelectAttribute.label,
                             assertion_operator=None, *assertion_expected): ...

    def get_text(self, selector, assertion_operator=None, assertion_expected=None): ...

    def get_textfield_value(self, selector, assertion_operator=None, assertion_expected=None): ...

    def get_title(self, assertion_operator=None, assertion_expected=None): ...

    def get_url(self, assertion_operator=None, assertion_expected=None): ...

    def get_viewport_size(self): ...

    def go_back(self): ...

    def go_forward(self): ...

    def go_to(self, url): ...

    def highlight_element(self, selector, duration='5s'): ...

    def local_storage_clear(self): ...

    def local_storage_get(self, key, assertion_operator=None, assertion_expected=None): ...

    def local_storage_remove(self, key): ...

    def local_storage_set(self, key, value): ...

    def open_browser(self, url=None, browser=SupportedBrowsers.chromium, headless=True): ...

    def press_keys(self, selector, *keys): ...

    def select_options_by(self, attribute, selector, *values): ...

    def session_storage_clear(self): ...

    def session_storage_get(self, key, assertion_operator=None, assertion_expected=None): ...

    def session_storage_remove(self, key): ...

    def session_storage_set(self, key, value): ...

    def set_timeout(self, timeout): ...

    def set_viewport_size(self, height, width): ...

    def switch_browser(self, index): ...

    def switch_context(self, index): ...

    def switch_page(self, index): ...

    def take_page_screenshot(self, path=None): ...

    def type_secret(self, selector, secret, delay='0 ms', clear=True): ...

    def type_text(self, selector, text, delay='0 ms', clear=True): ...

    def uncheck_checkbox(self, selector): ...

    def wait_for_elements_state(self, selector, state=ElementState.visible, timeout=None): ...
